#!/usr/bin/env bash

CUR_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

PROJ_TOP_PATH=${CUR_DIR}
DATASETS_PATH=${PROJ_TOP_PATH}/gamebet/datasets
export VIDEO_INPUT_PATH=${DATASETS_PATH}/0bfacc_5.mp4
export EXTERNAL_LIBS_PATH=${PROJ_TOP_PATH}/gamebet/thirdparts
export CHECKPOINTS_ROOT_PATH=${PROJ_TOP_PATH}/gamebet/checkpoints
export APP_OUTPUT_PATH=${CHECKPOINTS_ROOT_PATH}/output
export PYTHONPATH=${PROJ_TOP_PATH}/gamebet/app:${PROJ_TOP_PATH}/gamebet:${EXTERNAL_LIBS_PATH}/ByteTrack:${EXTERNAL_LIBS_PATH}/ultralytics

mkdir -p ${APP_OUTPUT_PATH}

# source ${CUR_DIR}/.venv/pytorch/bin/activate
